name: CI - Build & Dockerize
on:
  push:
    branches: ['master']

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Gradle build
        run: |
          gradle clean build
      - name: Docker login
        run: |
          echo ${{ secrets.DH_TOKEN }} | docker login -u ${{ secrets.DH_USER }} --password-stdin
      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.DH_USER }}/${{ github.event.repository.name }}:latest .
          docker push ${{ secrets.DH_USER }}/${{ github.event.repository.name }}:latest
